/*
 * generated by Xtext 2.15.0
 */
package fr.istic.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.videogen.ui.internal.VideogenActivator;

public class VideoGenUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return VideogenActivator.getInstance().getInjector("fr.istic.VideoGen");
	}

}
